language: node_js

node_js:
- "node"

cache:
  directories:
  - node_modules

install:
- npm install

script:
- true

deploy:
  provider: script
  skip_cleanup: true
  script: ./src/npm-prepack-publish.sh --user ${GEMFURY_USER} --api_key ${GEMFURY_API_KEY}
